[project]
name = "fim-eval"
version = "0.1.0"
requires-python = ">=3.7"
dependencies = [
    "human-eval-infilling",
    "openai>=1.59.9",
    "rich>=13.9.4",
]

[tool.uv.workspace]
members = [".", "packages/*"]

[tool.uv.sources]
human-eval-infilling = { workspace = true }
